# Generated by Django 3.1.1 on 2020-12-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activitie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('easy run', 'Easy Run'), ('marathon pace', 'Marathon Pace'), ('tempo', 'Tempo'), ('interval', 'Interval'), ('repetition', 'Repetition')], max_length=75)),
                ('distance', models.FloatField()),
                ('time', models.DurationField()),
                ('heartrate', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
