# Generated by Django 3.1.1 on 2020-12-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitie',
            name='type',
            field=models.CharField(choices=[('easy run', 'Easy Run'), ('marathon pace', 'Marathon Pace'), ('tempo', 'Tempo'), ('interval', 'Interval'), ('repetition', 'Repetition'), ('progressive', 'Progressive')], max_length=75),
        ),
    ]
