# Generated by Django 3.1.1 on 2020-12-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20201208_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitie',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
