# Generated by Django 3.1.1 on 2020-12-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20201208_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitie',
            name='heartrate',
            field=models.IntegerField(blank=True),
        ),
    ]
