# Generated by Django 3.1.1 on 2020-12-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_auto_20201208_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitie',
            name='type',
            field=models.CharField(choices=[('Easy Run', 'Easy Run'), ('Marathon Pace', 'Marathon Pace'), ('Tempo', 'Tempo'), ('Interval', 'Interval'), ('Repetition', 'Repetition'), ('Progressive', 'Progressive')], max_length=75),
        ),
    ]
