# Generated by Django 3.1.1 on 2020-12-09 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_auto_20201208_2017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activitie',
            new_name='Activity',
        ),
    ]
