# Generated by Django 3.1.1 on 2020-12-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_auto_20201209_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='sport',
            field=models.CharField(blank=True, choices=[('Running', 'Running'), ('Trail Running', 'Trail Running'), ('Strength Training', 'Strength Training')], max_length=75),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(blank=True, choices=[('Easy Run', 'Easy Run'), ('Marathon Pace', 'Marathon Pace'), ('Tempo', 'Tempo'), ('Interval', 'Interval'), ('Repetition', 'Repetition'), ('Progressive', 'Progressive'), ('Warm Up', 'Warm Up'), ('Cool Down', 'Cool Down'), ('Rest', 'Rest'), ('Jog', 'Jog')], max_length=75),
        ),
    ]
