# Generated by Django 3.1.1 on 2020-12-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_auto_20201209_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='sport',
            field=models.CharField(choices=[('Running', 'Running'), ('Trail Running', 'Trail Running'), ('Strength Training', 'Strength Training')], max_length=75),
        ),
    ]
