# Generated by Django 3.1.1 on 2020-12-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0029_auto_20201212_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='elevation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interval',
            name='elevation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
